FROM node:18-alpine

WORKDIR /app

RUN npm install -g json-server

COPY package*.json ./

RUN npm install

COPY database ./database

EXPOSE 3000

CMD ["json-server", "--watch", "database/db.json", "--host", "0.0.0.0"]